// Package index implements the agentmap index command: bulk indexing with task list generation.
package index

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/RKelln/agentmap/internal/config"
	"github.com/RKelln/agentmap/internal/discovery"
	"github.com/RKelln/agentmap/internal/generate"
	"github.com/RKelln/agentmap/internal/guide"
	"github.com/RKelln/agentmap/internal/navblock"
	"github.com/RKelln/agentmap/internal/parser"
)

// FileEntry is a file that has an AGENT:NAV block with a purpose field.
type FileEntry struct {
	RelPath string // relative to root, e.g. "docs/auth.md"
	Dir     string // directory part, e.g. "docs" (empty for root-level)
	Name    string // filename only, e.g. "auth.md"
	Purpose string // purpose field value (~ trimmed)
}

// TaskEntry is a file that needs agent-written descriptions.
type TaskEntry struct {
	RelPath      string
	LineCount    int
	SectionCount int
	Purpose      string   // current (may have ~ prefix)
	Sections     []string // section names with line ranges, e.g. "## Token Exchange [L45-112]"
	NavBlockRaw  string   // raw AGENT:NAV block text (for display in task list)
}

// Result is returned by BuildIndex.
type Result struct {
	Generated int    // skeletons generated
	TaskFiles int    // files added to task list
	Skipped   int    // already fully indexed (no ~)
	TaskPath  string // path to index-tasks.md (empty if dry-run)
}

// TaskListPath returns the path to the index-tasks.md file for a given repo root.
func TaskListPath(root string) string {
	return filepath.Join(root, ".agentmap", "index-tasks.md")
}

// CheckOffTaskEntry checks off the entry for relPath in the index-tasks.md at
// taskListPath if the file at filePath has no remaining ~ descriptions.
// It is a no-op if the task list does not exist or the entry is already checked.
// Errors are non-fatal — callers should warn but not fail.
func CheckOffTaskEntry(taskListPath, filePath, relPath string) error {
	// Read the file to check for remaining ~ descriptions.
	data, err := os.ReadFile(filePath)
	if err != nil {
		return fmt.Errorf("check off: read %s: %w", relPath, err)
	}
	pr := navblock.ParseNavBlock(string(data))
	if !pr.Found {
		return nil // no nav block, nothing to check off
	}
	if hasAutoGenerated(pr.Block) {
		return nil // still has ~ descriptions — don't check off yet
	}

	// Read the task list.
	taskData, err := os.ReadFile(taskListPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // no task list, nothing to do
		}
		return fmt.Errorf("check off: read task list: %w", err)
	}
	taskContent := string(taskData)

	// Find the entry header for this file: "## relPath (" anywhere in the file.
	entryHeader := "## " + relPath + " ("
	entryIdx := strings.Index(taskContent, entryHeader)
	if entryIdx < 0 {
		return nil // entry not in task list
	}

	// Find the range belonging to this entry: from the entry header to the
	// next "## " heading (or end of file). This prevents accidentally
	// checking off the wrong entry's checkbox when this entry is already
	// checked.
	afterHeader := taskContent[entryIdx:]
	nextHeader := strings.Index(afterHeader[len(entryHeader):], "\n## ")
	var entryRange string
	if nextHeader >= 0 {
		entryRange = afterHeader[:len(entryHeader)+nextHeader]
	} else {
		entryRange = afterHeader
	}

	// Find "- [ ]" within this entry's range only.
	checkboxIdx := strings.Index(entryRange, "- [ ]")
	if checkboxIdx < 0 {
		return nil // already checked or no checkbox found
	}

	// Replace the "- [ ]" within this entry with "- [x]".
	newTask := taskContent[:entryIdx] + entryRange[:checkboxIdx] + "- [x]" + entryRange[checkboxIdx+5:] + taskContent[entryIdx+len(entryRange):]
	if err := os.WriteFile(taskListPath, []byte(newTask), 0o644); err != nil {
		return fmt.Errorf("check off: write task list: %w", err)
	}
	return nil
}

func hasAutoGenerated(block navblock.NavBlock) bool {
	if navblock.IsAutoGenerated(block.Purpose) {
		return true
	}
	for _, e := range block.Nav {
		if navblock.IsAutoGenerated(e.About) {
			return true
		}
	}
	return false
}

// discoverMD finds markdown files relative to root using shared discovery logic.
// This respects gitignore when in a git repo and applies default excludes.
func discoverMD(root string, excludePatterns []string) ([]string, error) {
	files, err := discovery.DiscoverFiles(root, excludePatterns)
	if err != nil {
		return nil, fmt.Errorf("discover files under %s: %w", root, err)
	}
	return files, nil
}

// matchExclude reports whether relPath should be excluded by pat.
// filepath.Match does not support the ** glob (matches only one path segment).
// This function handles two extra cases:
//   - "dir/**": excludes any file whose path starts with "dir/"
//   - "dir": also matches as a directory prefix (equivalent to "dir/**")
func matchExclude(pat, rel string) bool {
	// Exact match or single-level glob via filepath.Match.
	if matched, _ := filepath.Match(pat, rel); matched {
		return true
	}
	// Match against just the filename component.
	if matched, _ := filepath.Match(pat, filepath.Base(rel)); matched {
		return true
	}
	// Handle "dir/**" recursive pattern: match any file under that directory.
	if strings.HasSuffix(pat, "/**") {
		prefix := pat[:len(pat)-3] // strip "/**"
		if rel == prefix || strings.HasPrefix(rel, prefix+"/") {
			return true
		}
	}
	// Handle bare "dir" pattern: treat it as a directory prefix match too.
	if !strings.Contains(pat, "/") && !strings.ContainsAny(pat, "*?[") {
		// bare name: already handled by filepath.Base match above
		return false
	}
	return false
}

func buildTaskEntry(root, relPath string, cfg config.Config) (TaskEntry, error) {
	fullPath := filepath.Join(root, relPath)
	data, err := os.ReadFile(fullPath)
	if err != nil {
		return TaskEntry{}, fmt.Errorf("read %s: %w", relPath, err)
	}
	content := string(data)
	// Use strings.Count to count actual newlines; strings.Split on a trailing
	// newline would produce a spurious empty element and inflate the count by 1.
	lineCount := strings.Count(content, "\n")

	pr := navblock.ParseNavBlock(content)
	purpose := ""
	var sections []string
	var navBlockRaw string

	if pr.Found {
		purpose = pr.Block.Purpose
		for _, e := range pr.Block.Nav {
			end := e.Start + e.N - 1
			sections = append(sections, fmt.Sprintf("%s [L%d-%d]", e.Name, e.Start, end))
		}
		// Extract the raw nav block text (inclusive of delimiters).
		rawLines := strings.Split(content, "\n")
		if pr.Start >= 1 && pr.End <= len(rawLines) {
			navBlockRaw = strings.Join(rawLines[pr.Start-1:pr.End], "\n")
		}
	} else {
		// No nav block yet; parse headings to build section list.
		headings, parseWarnings := parser.ParseHeadings(content, cfg.MaxDepth)
		for _, w := range parseWarnings {
			fmt.Fprintf(os.Stderr, "warning: %s: %s\n", relPath, w)
		}
		parsedSections := parser.ComputeSections(headings, lineCount)
		for _, s := range parsedSections {
			prefix := strings.Repeat("#", s.Depth)
			sections = append(sections, fmt.Sprintf("%s%s [L%d-%d]", prefix, s.Text, s.Start, s.End))
		}
	}

	return TaskEntry{
		RelPath:      relPath,
		LineCount:    lineCount,
		SectionCount: len(sections),
		Purpose:      purpose,
		Sections:     sections,
		NavBlockRaw:  navBlockRaw,
	}, nil
}

// renderTaskList renders the markdown task list for index-tasks.md.
func renderTaskList(tasks []TaskEntry) string {
	var b strings.Builder

	// Count progress.
	total := len(tasks)
	done := 0
	for _, t := range tasks {
		if !navblock.IsAutoGenerated(t.Purpose) && t.Purpose != "" {
			done++
		}
	}

	b.WriteString("# agentmap index tasks\n\n")
	fmt.Fprintf(&b, "Progress: %d/%d files complete\n\n", done, total)

	b.WriteString(`## Your job

Each file below has an AGENT:NAV block with ` + "`~`" + `-prefixed descriptions (auto-generated noise).
Rewrite every ` + "`~`" + ` value with a concise human description, then run ` + "`agentmap next`" + ` to advance.

**Workflow — repeat until done:**

1. Run ` + "`agentmap next`" + ` to get the next file to work on.
2. Read the file and rewrite every ` + "`~`" + `-prefixed ` + "`purpose`" + ` and ` + "`about`" + ` — remove the ` + "`~`" + `, replace keyword noise with a clear description.
3. Optionally add ` + "`see`" + ` entries for closely related files.
4. Save the file.
5. Run ` + "`agentmap next`" + ` again — it updates line numbers, checks off this file, and prints the next task.

When all entries are checked, ` + "`agentmap next`" + ` prints a completion message with the final ` + "`agentmap check`" + ` command.

---

## Rules (quick ref)

- ` + "`purpose`" + `: one-line file summary; under 10 words; semicolons not commas
	- ` + "`about`" + `: one-line section summary; don't restate the heading; under 10 words; leave blank if nothing to add
- ` + "`see`" + `: only add when another file must be read together with this one
- Never edit ` + "`s`" + `, ` + "`n`" + `, ` + "`nav[N]`" + `, or ` + "`see[N]`" + ` — only ` + "`purpose`" + `, ` + "`about`" + `, and ` + "`see`" + ` entries

---

## Example

**Before** (in the file):
` + "```" + `
<!-- AGENT:NAV
purpose:~token OAuth2 PKCE authentication flow
nav[2]{s,n,name,about}:
15,17,##Token Exchange,~OAuth2 PKCE authorization code token
32,15,##Token Refresh,~silent rotation expiry detection
-->
` + "```" + `

**After** (what you write):
` + "```" + `
<!-- AGENT:NAV
purpose:token lifecycle; OAuth2 exchange; refresh and revocation
nav[2]{s,n,name,about}:
15,17,##Token Exchange,OAuth2 code-for-token flow; PKCE required
32,15,##Token Refresh,silent rotation; sliding-window expiry
-->
` + "```" + `

Then run: ` + "`agentmap next`" + `

---

`)

	// Task entries.
	for _, t := range tasks {
		fmt.Fprintf(&b, "## %s (%d lines)\n\n", t.RelPath, t.LineCount)

		purposeCheck := "[ ]"
		if t.Purpose != "" && !navblock.IsAutoGenerated(t.Purpose) {
			purposeCheck = "[x]"
		}
		fmt.Fprintf(&b, "- %s\n\n", purposeCheck)

		if t.NavBlockRaw != "" {
			b.WriteString("```\n")
			b.WriteString(t.NavBlockRaw)
			b.WriteString("\n```\n\n")
		} else if len(t.Sections) > 0 {
			// Fallback: no raw block available, show section list.
			b.WriteString("Sections:\n")
			for _, s := range t.Sections {
				b.WriteString("  - " + s + "\n")
			}
			b.WriteString("\n")
		}
	}

	// Full guide (rules only) as appendix.
	b.WriteString("---\n\n")
	b.WriteString("# Appendix: Nav Writing Guide\n\n")
	b.WriteString(guide.RulesContent)
	b.WriteString("\n")

	return b.String()
}

// BuildIndex discovers files, generates skeletons for unindexed ones,
// and writes .agentmap/index-tasks.md. Returns a summary.
func BuildIndex(root string, cfg config.Config, dryRun, force bool) (Result, error) {
	files, err := discoverMD(root, cfg.Exclude)
	if err != nil {
		return Result{}, fmt.Errorf("index: discover files: %w", err)
	}

	var result Result
	var tasks []TaskEntry

	for _, relPath := range files {
		fullPath := filepath.Join(root, relPath)
		data, err := os.ReadFile(fullPath)
		if err != nil {
			return Result{}, fmt.Errorf("index: read %s: %w", relPath, err)
		}
		content := string(data)
		pr := navblock.ParseNavBlock(content)
		hasNavMarker := strings.Contains(content, "<!-- AGENT:NAV")

		switch {
		case force || (!pr.Found && !hasNavMarker):
			// Generate skeleton.
			if !dryRun {
				if _, err := generate.File(fullPath, cfg, false, true); err != nil {
					return Result{}, fmt.Errorf("index: generate %s: %w", relPath, err)
				}
			}
			result.Generated++
			task, err := buildTaskEntry(root, relPath, cfg)
			if err != nil {
				return Result{}, err
			}
			tasks = append(tasks, task)
			result.TaskFiles++

		case !pr.Found && hasNavMarker && !force:
			// Safety: do not overwrite files that appear to have a nav block marker
			// but fail to parse (often due malformed edits). Keep content intact and
			// add to task list for manual repair.
			fmt.Fprintf(os.Stderr, "warning: %s: AGENT:NAV marker found but block unparsable; skipping regeneration (use --force to overwrite)\n", relPath)
			task, err := buildTaskEntry(root, relPath, cfg)
			if err != nil {
				return Result{}, err
			}
			tasks = append(tasks, task)
			result.TaskFiles++

		case pr.Found && hasAutoGenerated(pr.Block):
			// Has ~ descriptions: add to task list, don't regenerate.
			task, err := buildTaskEntry(root, relPath, cfg)
			if err != nil {
				return Result{}, err
			}
			tasks = append(tasks, task)
			result.TaskFiles++

		default:
			// Fully reviewed: skip.
			result.Skipped++
		}
	}

	if !dryRun && len(tasks) > 0 {
		agentmapDir := filepath.Join(root, ".agentmap")
		if err := os.MkdirAll(agentmapDir, 0o755); err != nil {
			return Result{}, fmt.Errorf("index: create .agentmap dir: %w", err)
		}
		taskPath := filepath.Join(agentmapDir, "index-tasks.md")
		taskContent := renderTaskList(tasks)
		if err := os.WriteFile(taskPath, []byte(taskContent), 0o644); err != nil {
			return Result{}, fmt.Errorf("index: write task list: %w", err)
		}
		result.TaskPath = taskPath
	} else if !dryRun {
		// No tasks: remove stale task list and next-state so excluded
		// files don't leak into future `agentmap next` runs.
		agentmapDir := filepath.Join(root, ".agentmap")
		taskPath := filepath.Join(agentmapDir, "index-tasks.md")
		statePath := filepath.Join(agentmapDir, "next-state")
		_ = os.Remove(taskPath)
		_ = os.Remove(statePath)
	}

	return result, nil
}

// BuildFilesBlock reads all markdown files that have nav blocks and
// returns FileEntry list sorted by dir then name.
func BuildFilesBlock(root string, cfg config.Config) ([]FileEntry, error) {
	files, err := discoverMD(root, cfg.Exclude)
	if err != nil {
		return nil, fmt.Errorf("buildfilesblock: discover files: %w", err)
	}

	var entries []FileEntry
	for _, relPath := range files {
		fullPath := filepath.Join(root, relPath)
		data, err := os.ReadFile(fullPath)
		if err != nil {
			return nil, fmt.Errorf("buildfilesblock: read %s: %w", relPath, err)
		}
		pr := navblock.ParseNavBlock(string(data))
		if !pr.Found {
			continue
		}

		purpose := navblock.TrimAutoGenerated(pr.Block.Purpose)
		dir := filepath.ToSlash(filepath.Dir(relPath))
		if dir == "." {
			dir = ""
		}
		name := filepath.Base(relPath)

		entries = append(entries, FileEntry{
			RelPath: relPath,
			Dir:     dir,
			Name:    name,
			Purpose: purpose,
		})
	}

	// Sort: root-level (empty dir) first, then alphabetically by dir, then by name.
	sort.Slice(entries, func(i, j int) bool {
		di, dj := entries[i].Dir, entries[j].Dir
		if di != dj {
			if di == "" {
				return true
			}
			if dj == "" {
				return false
			}
			return di < dj
		}
		return entries[i].Name < entries[j].Name
	})

	return entries, nil
}

// buildFilesBlockText converts FileEntry list to navblock.FilesBlock and renders it.
// It reads each file to compute total line count (strings.Count("\n") — matches editor display).
func buildFilesBlockText(root string, entries []FileEntry) string {
	return buildFilesBlockTextWithLines(root, entries, 0)
}

// buildFilesBlockTextWithLines is like buildFilesBlockText but sets Lines on the FilesBlock.
// Pass lines=0 to omit lines:N from the rendered output.
func buildFilesBlockTextWithLines(root string, entries []FileEntry, lines int) string {
	fb := navblock.FilesBlock{
		Purpose: "Index of markdown files with agentmap nav blocks:",
		Lines:   lines,
	}
	for _, e := range entries {
		fileLines := 0
		fullPath := filepath.Join(root, e.RelPath)
		if data, err := os.ReadFile(fullPath); err == nil {
			fileLines = strings.Count(string(data), "\n")
		}
		fb.Entries = append(fb.Entries, navblock.FilesEntry{
			RelPath: e.RelPath,
			Lines:   fileLines,
			About:   e.Purpose,
		})
	}
	return navblock.RenderFilesBlock(fb)
}

// updateOrCreateAgentsMD writes or updates the inline files block in AGENTS.md.
// The block is appended at the end. Any existing files block (or legacy
// agentmap:index wrapper) is removed first.
func updateOrCreateAgentsMD(agentsMDPath, blockText string, dryRun bool) error {
	if dryRun {
		return nil
	}

	var content string
	data, err := os.ReadFile(agentsMDPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", agentsMDPath, err)
	} else if err == nil {
		content = string(data)
	}

	// Remove existing AGENT:NAV files block if present.
	if navIdx := strings.Index(content, "<!-- AGENT:NAV\n"); navIdx >= 0 {
		if closeIdx := strings.Index(content[navIdx:], "\n-->"); closeIdx >= 0 {
			closeIdx = navIdx + closeIdx + len("\n-->")
			content = content[:navIdx] + content[closeIdx:]
		}
	}

	// Clean up legacy agentmap:index wrappers (transitional).
	for _, marker := range []string{"<!-- agentmap:index -->", "<!-- /agentmap:index -->"} {
		content = strings.ReplaceAll(content, marker+"\n", "")
		content = strings.ReplaceAll(content, "\n"+marker, "")
		content = strings.ReplaceAll(content, marker, "")
	}

	// Normalize leading whitespace after cleanup.
	content = strings.TrimLeft(content, "\n")

	// Append block at end.
	content = strings.TrimRight(content, "\n")
	content += "\n\n" + blockText + "\n"

	return os.WriteFile(agentsMDPath, []byte(content), 0o644)
}

// RefreshFilesBlock rebuilds the AGENTMAP.md (or AGENTS.md inline block) from the current
// purpose fields of all indexed files. Called by update after refreshing nav blocks so that
// the files index stays in sync without requiring a full agentmap index run.
func RefreshFilesBlock(root string, cfg config.Config, dryRun bool) error {
	entries, err := BuildFilesBlock(root, cfg)
	if err != nil {
		return fmt.Errorf("refreshfilesblock: %w", err)
	}
	if len(entries) == 0 {
		return nil
	}
	if _, err := WriteFilesBlock(root, entries, cfg, dryRun); err != nil {
		return fmt.Errorf("refreshfilesblock: %w", err)
	}
	return nil
}

// WriteFilesBlock writes the files block to AGENTS.md (inline) or AGENTMAP.md (dedicated).
// Returns the destination path.
func WriteFilesBlock(root string, entries []FileEntry, cfg config.Config, dryRun bool) (string, error) {
	blockText := buildFilesBlockText(root, entries)
	agentsMDPath := filepath.Join(root, "AGENTS.md")

	if len(entries) <= cfg.IndexInlineMax {
		// Small project: inline in AGENTS.md. lines:N not written for inline blocks
		// (the block is embedded inside AGENTS.md, not the whole file).
		if err := updateOrCreateAgentsMD(agentsMDPath, blockText, dryRun); err != nil {
			return "", fmt.Errorf("writefilesblock: update AGENTS.md: %w", err)
		}
		return agentsMDPath, nil
	}

	// Large project: write AGENTMAP.md + pointer in AGENTS.md.
	// Compute lines:N from the final file content (blockText + trailing newline).
	// Adding lines:N itself adds one line, so add 1 to the count before inserting.
	finalContent := blockText + "\n"
	totalLines := strings.Count(finalContent, "\n") + 1 // +1 for the lines:N line itself
	if totalLines > 0 {
		finalContent = buildFilesBlockTextWithLines(root, entries, totalLines) + "\n"
	}

	agentmapMDPath := filepath.Join(root, "AGENTMAP.md")
	if !dryRun {
		if err := os.WriteFile(agentmapMDPath, []byte(finalContent), 0o644); err != nil {
			return "", fmt.Errorf("writefilesblock: write AGENTMAP.md: %w", err)
		}
	}
	return agentmapMDPath, nil
}
