// Package index implements the agentmap index command: bulk indexing with task list generation.
package index

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ryankelln/agentmap/internal/config"
	"github.com/ryankelln/agentmap/internal/generate"
	"github.com/ryankelln/agentmap/internal/navblock"
	"github.com/ryankelln/agentmap/internal/parser"
)

// FileEntry is a file that has an AGENT:NAV block with a purpose field.
type FileEntry struct {
	RelPath string // relative to root, e.g. "docs/auth.md"
	Dir     string // directory part, e.g. "docs" (empty for root-level)
	Name    string // filename only, e.g. "auth.md"
	Purpose string // purpose field value (~ trimmed)
}

// TaskEntry is a file that needs agent-written descriptions.
type TaskEntry struct {
	RelPath      string
	LineCount    int
	SectionCount int
	Purpose      string   // current (may have ~ prefix)
	Sections     []string // section names with line ranges, e.g. "## Token Exchange [L45-112]"
}

// Result is returned by BuildIndex.
type Result struct {
	Generated int    // skeletons generated
	TaskFiles int    // files added to task list
	Skipped   int    // already fully indexed (no ~)
	TaskPath  string // path to index-tasks.md (empty if dry-run)
}

// hasAutoGenerated returns true if any description field in the nav block has the ~ prefix.
func hasAutoGenerated(block navblock.NavBlock) bool {
	if navblock.IsAutoGenerated(block.Purpose) {
		return true
	}
	for _, e := range block.Nav {
		if navblock.IsAutoGenerated(e.About) {
			return true
		}
	}
	return false
}

// discoverMD walks a directory (non-git) to find all .md files relative to root.
// It excludes the .agentmap/ directory.
func discoverMD(root string, excludePatterns []string) ([]string, error) {
	var files []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		rel = filepath.ToSlash(rel)

		if info.IsDir() {
			// Skip .agentmap directory.
			if rel == ".agentmap" || strings.HasPrefix(rel, ".agentmap/") {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(rel, ".md") {
			return nil
		}
		for _, pat := range excludePatterns {
			if matchExclude(pat, rel) {
				return nil
			}
		}
		files = append(files, rel)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk %s: %w", root, err)
	}
	sort.Strings(files)
	return files, nil
}

// matchExclude reports whether relPath should be excluded by pat.
// filepath.Match does not support the ** glob (matches only one path segment).
// This function handles two extra cases:
//   - "dir/**": excludes any file whose path starts with "dir/"
//   - "dir": also matches as a directory prefix (equivalent to "dir/**")
func matchExclude(pat, rel string) bool {
	// Exact match or single-level glob via filepath.Match.
	if matched, _ := filepath.Match(pat, rel); matched {
		return true
	}
	// Match against just the filename component.
	if matched, _ := filepath.Match(pat, filepath.Base(rel)); matched {
		return true
	}
	// Handle "dir/**" recursive pattern: match any file under that directory.
	if strings.HasSuffix(pat, "/**") {
		prefix := pat[:len(pat)-3] // strip "/**"
		if rel == prefix || strings.HasPrefix(rel, prefix+"/") {
			return true
		}
	}
	// Handle bare "dir" pattern: treat it as a directory prefix match too.
	if !strings.Contains(pat, "/") && !strings.ContainsAny(pat, "*?[") {
		// bare name: already handled by filepath.Base match above
		return false
	}
	return false
}

func buildTaskEntry(root, relPath string, cfg config.Config) (TaskEntry, error) {
	fullPath := filepath.Join(root, relPath)
	data, err := os.ReadFile(fullPath)
	if err != nil {
		return TaskEntry{}, fmt.Errorf("read %s: %w", relPath, err)
	}
	content := string(data)
	// Use strings.Count to count actual newlines; strings.Split on a trailing
	// newline would produce a spurious empty element and inflate the count by 1.
	lineCount := strings.Count(content, "\n")

	pr := navblock.ParseNavBlock(content)
	purpose := ""
	var sections []string

	if pr.Found {
		purpose = pr.Block.Purpose
		for _, e := range pr.Block.Nav {
			end := e.Start + e.N - 1
			sections = append(sections, fmt.Sprintf("%s [L%d-%d]", e.Name, e.Start, end))
		}
	} else {
		// No nav block yet; parse headings to build section list.
		headings := parser.ParseHeadings(content, cfg.MaxDepth)
		parsedSections := parser.ComputeSections(headings, lineCount)
		for _, s := range parsedSections {
			prefix := strings.Repeat("#", s.Depth)
			sections = append(sections, fmt.Sprintf("%s%s [L%d-%d]", prefix, s.Text, s.Start, s.End))
		}
	}

	return TaskEntry{
		RelPath:      relPath,
		LineCount:    lineCount,
		SectionCount: len(sections),
		Purpose:      purpose,
		Sections:     sections,
	}, nil
}

// renderTaskList renders the markdown task list for index-tasks.md.
func renderTaskList(tasks []TaskEntry) string {
	var b strings.Builder
	b.WriteString("# agentmap index tasks\n\n")
	b.WriteString("See docs/nav-writing-guide.md for instructions on writing descriptions.\n\n")

	// Count checked items for progress (only purpose lines marked [x]).
	total := len(tasks)
	done := 0
	for _, t := range tasks {
		if !navblock.IsAutoGenerated(t.Purpose) && t.Purpose != "" {
			done++
		}
	}
	fmt.Fprintf(&b, "Progress: %d/%d files complete\n", done, total)

	for _, t := range tasks {
		fmt.Fprintf(&b, "\n## %s (%d lines, %d sections)\n\n", t.RelPath, t.LineCount, t.SectionCount)

		purposeCheck := "[ ]"
		if t.Purpose != "" && !navblock.IsAutoGenerated(t.Purpose) {
			purposeCheck = "[x]"
		}
		fmt.Fprintf(&b, "- %s purpose: %s\n", purposeCheck, t.Purpose)

		sectionsCheck := "[ ]"
		allSectionsDone := len(t.Sections) > 0
		// We can't check per-section from the nav block alone; use [ ] by default.
		_ = allSectionsDone
		fmt.Fprintf(&b, "- %s sections (%d):\n", sectionsCheck, t.SectionCount)
		for _, s := range t.Sections {
			b.WriteString("  - " + s + "\n")
		}
	}

	return b.String()
}

// BuildIndex discovers files, generates skeletons for unindexed ones,
// and writes .agentmap/index-tasks.md. Returns a summary.
func BuildIndex(root string, cfg config.Config, dryRun bool, force bool) (Result, error) {
	files, err := discoverMD(root, cfg.Exclude)
	if err != nil {
		return Result{}, fmt.Errorf("index: discover files: %w", err)
	}

	var result Result
	var tasks []TaskEntry

	for _, relPath := range files {
		fullPath := filepath.Join(root, relPath)
		data, err := os.ReadFile(fullPath)
		if err != nil {
			return Result{}, fmt.Errorf("index: read %s: %w", relPath, err)
		}
		content := string(data)
		pr := navblock.ParseNavBlock(content)

		switch {
		case force || !pr.Found:
			// Generate skeleton.
			if !dryRun {
				if _, err := generate.File(fullPath, cfg, false); err != nil {
					return Result{}, fmt.Errorf("index: generate %s: %w", relPath, err)
				}
			}
			result.Generated++
			task, err := buildTaskEntry(root, relPath, cfg)
			if err != nil {
				return Result{}, err
			}
			tasks = append(tasks, task)
			result.TaskFiles++

		case pr.Found && hasAutoGenerated(pr.Block):
			// Has ~ descriptions: add to task list, don't regenerate.
			task, err := buildTaskEntry(root, relPath, cfg)
			if err != nil {
				return Result{}, err
			}
			tasks = append(tasks, task)
			result.TaskFiles++

		default:
			// Fully reviewed: skip.
			result.Skipped++
		}
	}

	if !dryRun && len(tasks) > 0 {
		agentmapDir := filepath.Join(root, ".agentmap")
		if err := os.MkdirAll(agentmapDir, 0o755); err != nil {
			return Result{}, fmt.Errorf("index: create .agentmap dir: %w", err)
		}
		taskPath := filepath.Join(agentmapDir, "index-tasks.md")
		taskContent := renderTaskList(tasks)
		if err := os.WriteFile(taskPath, []byte(taskContent), 0o644); err != nil {
			return Result{}, fmt.Errorf("index: write task list: %w", err)
		}
		result.TaskPath = taskPath
	}

	return result, nil
}

// BuildFilesBlock reads all markdown files that have nav blocks and
// returns FileEntry list sorted by dir then name.
func BuildFilesBlock(root string, cfg config.Config) ([]FileEntry, error) {
	files, err := discoverMD(root, cfg.Exclude)
	if err != nil {
		return nil, fmt.Errorf("buildfilesblock: discover files: %w", err)
	}

	var entries []FileEntry
	for _, relPath := range files {
		fullPath := filepath.Join(root, relPath)
		data, err := os.ReadFile(fullPath)
		if err != nil {
			return nil, fmt.Errorf("buildfilesblock: read %s: %w", relPath, err)
		}
		pr := navblock.ParseNavBlock(string(data))
		if !pr.Found {
			continue
		}

		purpose := navblock.TrimAutoGenerated(pr.Block.Purpose)
		dir := filepath.ToSlash(filepath.Dir(relPath))
		if dir == "." {
			dir = ""
		}
		name := filepath.Base(relPath)

		entries = append(entries, FileEntry{
			RelPath: relPath,
			Dir:     dir,
			Name:    name,
			Purpose: purpose,
		})
	}

	// Sort: root-level (empty dir) first, then alphabetically by dir, then by name.
	sort.Slice(entries, func(i, j int) bool {
		di, dj := entries[i].Dir, entries[j].Dir
		if di != dj {
			if di == "" {
				return true
			}
			if dj == "" {
				return false
			}
			return di < dj
		}
		return entries[i].Name < entries[j].Name
	})

	return entries, nil
}

const (
	agentmapIndexOpen  = "<!-- agentmap:index -->"
	agentmapIndexClose = "<!-- /agentmap:index -->"
)

// buildFilesBlockText converts FileEntry list to navblock.FilesBlock and renders it.
func buildFilesBlockText(root string, entries []FileEntry) string {
	repoName := filepath.Base(filepath.Clean(root))
	if repoName == "." || repoName == "" {
		// Fallback: use absolute path base.
		if abs, err := filepath.Abs(root); err == nil {
			repoName = filepath.Base(abs)
		}
	}
	fb := navblock.FilesBlock{
		Purpose: "project file index for " + repoName,
	}
	for _, e := range entries {
		fb.Entries = append(fb.Entries, navblock.FilesEntry{
			RelPath: e.RelPath,
			About:   e.Purpose,
		})
	}
	return navblock.RenderFilesBlock(fb)
}

// updateOrCreateAgentsMD writes or updates the inline agentmap:index block in AGENTS.md.
func updateOrCreateAgentsMD(agentsMDPath, blockText string, dryRun bool) error {
	if dryRun {
		return nil
	}

	var existingContent string
	data, err := os.ReadFile(agentsMDPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", agentsMDPath, err)
	} else if err == nil {
		existingContent = string(data)
	}

	newSection := agentmapIndexOpen + "\n" + blockText + "\n" + agentmapIndexClose

	if strings.Contains(existingContent, agentmapIndexOpen) {
		// Replace existing section.
		start := strings.Index(existingContent, agentmapIndexOpen)
		end := strings.Index(existingContent, agentmapIndexClose)
		if end >= 0 {
			end += len(agentmapIndexClose)
		} else {
			end = len(existingContent)
		}
		existingContent = existingContent[:start] + newSection + existingContent[end:]
	} else {
		// Prepend to file.
		if existingContent == "" {
			existingContent = newSection + "\n"
		} else {
			existingContent = newSection + "\n\n" + existingContent
		}
	}

	return os.WriteFile(agentsMDPath, []byte(existingContent), 0o644)
}

// ensureAgentsMDPointer ensures AGENTS.md contains the pointer line to AGENTMAP.md.
func ensureAgentsMDPointer(agentsMDPath string, dryRun bool) error {
	if dryRun {
		return nil
	}
	const pointerLine = "See AGENTMAP.md for the full file index."
	var existing string
	data, err := os.ReadFile(agentsMDPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", agentsMDPath, err)
	} else if err == nil {
		existing = string(data)
	}
	if strings.Contains(existing, pointerLine) {
		return nil
	}
	if existing == "" {
		existing = pointerLine + "\n"
	} else {
		existing = existing + "\n" + pointerLine + "\n"
	}
	return os.WriteFile(agentsMDPath, []byte(existing), 0o644)
}

// WriteFilesBlock writes the files block to AGENTS.md (inline) or AGENTMAP.md (dedicated).
// Returns the destination path.
func WriteFilesBlock(root string, entries []FileEntry, cfg config.Config, dryRun bool) (string, error) {
	blockText := buildFilesBlockText(root, entries)
	agentsMDPath := filepath.Join(root, "AGENTS.md")

	if len(entries) <= cfg.IndexInlineMax {
		// Small project: inline in AGENTS.md.
		if err := updateOrCreateAgentsMD(agentsMDPath, blockText, dryRun); err != nil {
			return "", fmt.Errorf("writefilesblock: update AGENTS.md: %w", err)
		}
		return agentsMDPath, nil
	}

	// Large project: write AGENTMAP.md + pointer in AGENTS.md.
	agentmapMDPath := filepath.Join(root, "AGENTMAP.md")
	if !dryRun {
		if err := os.WriteFile(agentmapMDPath, []byte(blockText+"\n"), 0o644); err != nil {
			return "", fmt.Errorf("writefilesblock: write AGENTMAP.md: %w", err)
		}
		if err := ensureAgentsMDPointer(agentsMDPath, dryRun); err != nil {
			return "", fmt.Errorf("writefilesblock: update AGENTS.md pointer: %w", err)
		}
	}
	return agentmapMDPath, nil
}
