// Package update implements the agentmap update command.
package update

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/RKelln/agentmap/internal/config"
	"github.com/RKelln/agentmap/internal/discovery"
	"github.com/RKelln/agentmap/internal/generate"
	"github.com/RKelln/agentmap/internal/gitutil"
	"github.com/RKelln/agentmap/internal/index"
	"github.com/RKelln/agentmap/internal/navblock"
	"github.com/RKelln/agentmap/internal/parser"
)

// ReportType indicates the type of update report entry.
type ReportType int

const (
	// ReportOK means heading matched and line numbers unchanged.
	ReportOK ReportType = iota
	// ReportShifted means heading matched but line numbers changed.
	ReportShifted
	// ReportContentChanged means section has content changes from git diff.
	ReportContentChanged
	// ReportNew means new heading with no description.
	ReportNew
	// ReportDeleted means heading removed from document.
	ReportDeleted
)

// noChanges is returned when a file has no nav block or no changes needed.
const noChanges = "no-changes"

// ReportEntry represents a single entry in the update report.
type ReportEntry struct {
	Type            ReportType
	Name            string
	OldStart        int
	OldEnd          int
	NewStart        int
	NewEnd          int
	ModifiedCount   int
	CurrentAbout    string
	IsAutoGenerated bool // true if CurrentAbout starts with ~
}

func (r ReportEntry) String() string {
	switch r.Type {
	case ReportOK:
		return fmt.Sprintf("  OK: %s (%d-%d)", r.Name, r.NewStart, r.NewEnd)
	case ReportShifted:
		return fmt.Sprintf("  shifted: %s (%d-%d -> %d-%d)", r.Name, r.OldStart, r.OldEnd, r.NewStart, r.NewEnd)
	case ReportContentChanged:
		desc := fmt.Sprintf("%q", r.CurrentAbout)
		if r.IsAutoGenerated {
			desc += " (auto-generated; needs review)"
		}
		return fmt.Sprintf("  content-changed: %s (lines %d-%d; %d lines modified)\n    current description: %s", r.Name, r.NewStart, r.NewEnd, r.ModifiedCount, desc)
	case ReportNew:
		return fmt.Sprintf("  new: %s (%d-%d; no description)", r.Name, r.NewStart, r.NewEnd)
	case ReportDeleted:
		return fmt.Sprintf("  deleted: %s (removed from document)", r.Name)
	default:
		return ""
	}
}

// Update discovers markdown files with nav blocks under root and updates line numbers.
// repoRoot is the repository root where AGENTS.md/AGENTMAP.md should be written.
// When repoRoot is empty it falls back to root (single-root usage).
func Update(root, repoRoot string, cfg config.Config, dryRun, quiet bool) error {
	if repoRoot == "" {
		repoRoot = root
	}

	files, err := discovery.DiscoverFiles(root, cfg.Exclude)
	if err != nil {
		return fmt.Errorf("update: discover files: %w", err)
	}

	// §12.4: one git diff call for the whole repo, not one per file.
	repoChanges, err := gitutil.RepoChanges(".")
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: git diff: %v; content-change detection disabled\n", err)
	}

	var anyChanged bool
	taskListPath := index.TaskListPath(repoRoot)
	for _, f := range files {
		fullPath := filepath.Join(root, f)
		var changedLines []gitutil.LineRange
		if repoChanges != nil {
			changedLines = repoChanges[f]
		}
		report, err := File(fullPath, cfg, dryRun, quiet, changedLines)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %s: %v\n", f, err)
			continue
		}
		if report != noChanges {
			anyChanged = true
			if !quiet {
				fmt.Println(report)
			}
		}
		// Auto-check the task list entry if the file is now fully reviewed.
		if !dryRun {
			if err := index.CheckOffTaskEntry(taskListPath, fullPath, f); err != nil {
				fmt.Fprintf(os.Stderr, "warning: %s: task list check-off: %v\n", f, err)
			}
		}
	}

	if len(files) > 0 && !anyChanged {
		fmt.Println("No changes")
	}

	// Refresh AGENTMAP.md (or inline AGENTS.md block) at the repo root so the
	// files index stays in sync with any purpose fields that may have been updated
	// in nav blocks. Always use repoRoot — never the scan subdir — so that the
	// index file is written to the correct location.
	if !dryRun {
		if err := index.RefreshFilesBlock(repoRoot, cfg, false); err != nil {
			fmt.Fprintf(os.Stderr, "warning: refresh files block: %v\n", err)
		}
	}

	return nil
}

// File processes a single markdown file and updates its nav block.
// changedLines contains pre-computed git diff ranges for this file; if nil, falls back
// to per-file git diff (for direct single-file calls from CLI).
// Returns noChanges if the file has no nav block or no changes needed.
func File(path string, cfg config.Config, dryRun, quiet bool, changedLines ...[]gitutil.LineRange) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("update: read file: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	// Use strings.Count for totalLines rather than len(lines): strings.Split
	// produces a spurious trailing empty element for POSIX files ending with \n,
	// overcounting by 1. strings.Count("\n") equals wc -l.
	totalLines := strings.Count(string(content), "\n")

	pr := navblock.ParseNavBlock(string(content))
	oldBlock, hasBlock, corrupted := pr.Block, pr.Found, pr.Corrupted
	if corrupted {
		fmt.Fprintf(os.Stderr, "warning: %s: nav block is corrupted — run 'agentmap generate' to regenerate\n", path)
		return noChanges, nil
	}
	if !hasBlock {
		// No nav block: delegate to generate so that `update <dir>` works on
		// a mixed directory containing both new and already-indexed files.
		report, err := generate.File(path, cfg, dryRun, true)
		if err != nil {
			return "", fmt.Errorf("update: generate nav block for %s: %w", path, err)
		}
		return report, nil
	}

	// Compute content lines (total newlines minus the nav block itself).
	contentLines := strings.Count(string(content), "\n") - (pr.End - pr.Start + 1)
	if contentLines < 0 {
		contentLines = 0
	}

	headings, parseWarnings := parser.ParseHeadings(string(content), cfg.MaxDepth)
	for _, w := range parseWarnings {
		fmt.Fprintf(os.Stderr, "warning: %s: %s\n", path, w)
	}
	sections := parser.ComputeSections(headings, totalLines)

	// Handle purpose-only files: no headings, but lines:N may still need updating.
	if len(headings) == 0 {
		// Check for content changes even when no headings
		var fileChanges []gitutil.LineRange
		if len(changedLines) > 0 && changedLines[0] != nil {
			fileChanges = changedLines[0]
		} else {
			fileChanges = getChangedLines(path)
		}
		hasContentChange := len(fileChanges) > 0

		// Only refresh lines:N if the block already has it (non-zero) or content changed
		linesChanged := oldBlock.Lines != 0 && oldBlock.Lines != totalLines
		if !linesChanged && !hasContentChange {
			return noChanges, nil
		}

		// If content changed with no headings, report content-changed
		if hasContentChange {
			reports := []ReportEntry{{
				Type:          ReportContentChanged,
				Name:          "# (purpose-only)",
				NewStart:      1,
				NewEnd:        totalLines,
				ModifiedCount: fileChanges[0].End - fileChanges[0].Start + 1,
				CurrentAbout:  oldBlock.Purpose,
			}}
			if !quiet {
				return formatReport(path, reports), nil
			}
			return noChanges, nil
		}

		oldLinesCount := oldBlock.Lines
		oldBlock.Lines = totalLines
		blockText := navblock.RenderNavBlock(oldBlock)
		if dryRun {
			return fmt.Sprintf("Updated: %s\n  lines-updated: %d -> %d", path, oldLinesCount, totalLines), nil
		}
		newContent := navblock.InsertNavBlock(string(content), blockText)
		if err := os.WriteFile(path, []byte(newContent), 0o644); err != nil {
			return "", fmt.Errorf("update: write file: %w", err)
		}
		if quiet {
			return noChanges, nil
		}
		return fmt.Sprintf("Updated: %s\n  lines-updated: %d -> %d", path, oldLinesCount, totalLines), nil
	}

	// If the existing nav block has no nav entries and the file is below MinLines,
	// generate intentionally wrote a purpose-only block for this file. Don't add
	// new nav entries here — only refresh lines:N to stay consistent with generate.
	if len(oldBlock.Nav) == 0 && contentLines < cfg.MinLines {
		linesChanged := oldBlock.Lines != 0 && oldBlock.Lines != totalLines
		if !linesChanged {
			return noChanges, nil
		}
		oldLinesCount := oldBlock.Lines
		oldBlock.Lines = totalLines
		blockText := navblock.RenderNavBlock(oldBlock)
		if dryRun {
			return fmt.Sprintf("Updated: %s\n  lines-updated: %d -> %d", path, oldLinesCount, totalLines), nil
		}
		newContent := navblock.InsertNavBlock(string(content), blockText)
		if err := os.WriteFile(path, []byte(newContent), 0o644); err != nil {
			return "", fmt.Errorf("update: write file: %w", err)
		}
		if quiet {
			return noChanges, nil
		}
		return fmt.Sprintf("Updated: %s\n  lines-updated: %d -> %d", path, oldLinesCount, totalLines), nil
	}

	// Get file changes for content detection (or nil if not provided)
	var fileChanges []gitutil.LineRange
	if len(changedLines) > 0 && changedLines[0] != nil {
		fileChanges = changedLines[0]
	} else {
		fileChanges = getChangedLines(path)
	}

	// Filter out changes entirely within the nav block — those are description
	// edits, not section content changes. Without this, freshly-generated or
	// recently-edited nav blocks would incorrectly report every section as
	// content-changed even when only the nav block itself was modified.
	if len(fileChanges) > 0 && len(sections) > 0 && pr.Found {
		firstContentLine := sections[0].Start
		filtered := fileChanges[:0]
		for _, cl := range fileChanges {
			if cl.End >= firstContentLine {
				filtered = append(filtered, cl)
			}
		}
		fileChanges = filtered
	}
	entryReports := buildEntryReports(oldBlock.Nav, sections, fileChanges)

	hasChanges := (oldBlock.Lines != 0 && oldBlock.Lines != totalLines)
	for _, er := range entryReports {
		if er.Type != ReportOK {
			hasChanges = true
			break
		}
	}

	if !hasChanges {
		return noChanges, nil
	}

	block := buildUpdatedBlock(oldBlock, sections, entryReports, lines, cfg, contentLines, totalLines)
	blockText := navblock.RenderNavBlock(block)

	// If the new nav block is a different size than the old one (entries added or
	// removed), all content line numbers shift by that delta. Apply the same offset
	// correction that generate uses, so the file is correct in a single pass.
	newBlockLines := len(strings.Split(blockText, "\n"))
	oldBlockLineCount := pr.End - pr.Start + 1
	if offset := newBlockLines - oldBlockLineCount; offset != 0 {
		for i := range block.Nav {
			block.Nav[i].Start += offset
		}
		for i := range entryReports {
			entryReports[i].NewStart += offset
			entryReports[i].NewEnd += offset
		}
		blockText = navblock.RenderNavBlock(block)
	}

	// Remove "new" entries that were collapsed into >hints by PruneNavEntries.
	// These entries don't need individual abouts — they're represented as hints
	// on their parent entry. Reporting them as "new (no description)" is misleading.
	entryReports = filterHintedNewEntries(entryReports, block.Nav)

	if dryRun {
		return formatReport(path, entryReports), nil
	}

	newContent := navblock.InsertNavBlock(string(content), blockText)
	if err := os.WriteFile(path, []byte(newContent), 0o644); err != nil {
		return "", fmt.Errorf("update: write file: %w", err)
	}

	if quiet {
		return noChanges, nil
	}
	return formatReport(path, entryReports), nil
}

func getChangedLines(path string) []gitutil.LineRange {
	ranges, err := gitutil.FileChanges(path)
	if err != nil || ranges == nil {
		return nil
	}
	return ranges
}

// navIndex builds an index from normalised heading name to all nav entries with
// that name. Duplicate heading names are supported: callers pick the best match
// by proximity using pickClosest.
func navIndex(nav []navblock.NavEntry) map[string][]navblock.NavEntry {
	idx := make(map[string][]navblock.NavEntry, len(nav))
	for _, e := range nav {
		key := navblock.NormalizeHeading(e.Name)
		idx[key] = append(idx[key], e)
	}
	return idx
}

func abs(x int) int {
	if x < 0 {
		return -x
	}
	return x
}

// matchSectionsToNav maps each section to its best old nav entry using two passes:
//  1. Exact: section.Start == entry.Start (no ambiguity)
//  2. Minimum-distance: for unmatched sections, sort all (section, entry) candidate
//     pairs by distance and assign greedily from closest outward, so each entry is
//     consumed by the section that is truly nearest to it — not just the first
//     section encountered in document order.
//
// This ensures that when a document has more occurrences of a heading name than
// the nav block, the stored entry is paired with the section at the same line
// (pass 1), and when the section has shifted, the nearest occurrence wins
// rather than whatever happens to come first in the file.
//
// Returns a map from section index → matched NavEntry, and the set of matched
// entry Start values.
func matchSectionsToNav(sections []parser.Section, byName map[string][]navblock.NavEntry) (map[int]navblock.NavEntry, map[int]bool) {
	matched := make(map[int]navblock.NavEntry, len(sections))
	usedStart := make(map[int]bool)

	// Pass 1: exact line-number matches.
	for i, s := range sections {
		key := navblock.NormalizeHeading(s.Text)
		candidates := byName[key]
		for j, e := range candidates {
			if e.Start == s.Start {
				matched[i] = e
				usedStart[e.Start] = true
				byName[key] = append(candidates[:j:j], candidates[j+1:]...)
				break
			}
		}
	}

	// Pass 2: minimum-distance matching for remaining sections.
	// Build all (section_idx, entry, distance) triples from unmatched sections
	// and remaining entries, then sort by distance and assign greedily from
	// closest outward so that the best pairing wins regardless of section order.
	type candidate struct {
		sectionIdx int
		entry      navblock.NavEntry
		dist       int
	}
	var candidates []candidate
	for i, s := range sections {
		if _, ok := matched[i]; ok {
			continue
		}
		key := navblock.NormalizeHeading(s.Text)
		for _, e := range byName[key] {
			candidates = append(candidates, candidate{i, e, abs(e.Start - s.Start)})
		}
	}
	sort.Slice(candidates, func(a, b int) bool {
		return candidates[a].dist < candidates[b].dist
	})

	consumedSection := make(map[int]bool)
	consumedEntry := make(map[int]bool) // keyed by entry.Start
	for _, c := range candidates {
		if consumedSection[c.sectionIdx] || consumedEntry[c.entry.Start] {
			continue
		}
		matched[c.sectionIdx] = c.entry
		usedStart[c.entry.Start] = true
		consumedSection[c.sectionIdx] = true
		consumedEntry[c.entry.Start] = true
	}

	return matched, usedStart
}

func buildEntryReports(oldNav []navblock.NavEntry, sections []parser.Section, changedLines []gitutil.LineRange) []ReportEntry {
	var reports []ReportEntry

	// Build multi-map: name -> []NavEntry to handle duplicate heading names.
	// matchSectionsToNav uses exact-match first, then proximity — ensuring each
	// nav entry is paired with the section at the same absolute line before
	// falling back to nearest duplicate.
	byName := navIndex(oldNav)
	sectionToEntry, usedStart := matchSectionsToNav(sections, byName)

	for i, s := range sections {
		prefix := strings.Repeat("#", s.Depth)
		name := prefix + navblock.NormalizeHeading(s.Text)

		oldEntry, found := sectionToEntry[i]

		if !found {
			// New section not in existing nav block.
			// All new sections are reported — including h3s — consistent with
			// buildUpdatedBlock which now includes all sections unconditionally
			// and delegates budget enforcement to PruneNavEntries.
			reports = append(reports, ReportEntry{
				Type:     ReportNew,
				Name:     name,
				NewStart: s.Start,
				NewEnd:   s.End,
			})
			continue
		}

		// Check content changes FIRST (higher priority than shifted)
		modifiedCount := 0
		if len(changedLines) > 0 {
			for _, cl := range changedLines {
				if s.Start <= cl.End && s.End >= cl.Start {
					clLen := cl.End - cl.Start + 1
					if clLen > modifiedCount {
						modifiedCount = clLen
					}
				}
			}
		}

		// Determine report type: content-changed takes priority over shifted/OK
		reportType := ReportOK
		if modifiedCount > 0 {
			reportType = ReportContentChanged
		} else if oldEntry.Start != s.Start || oldEntry.Start+oldEntry.N-1 != s.End {
			reportType = ReportShifted
		}

		reports = append(reports, ReportEntry{
			Type:            reportType,
			Name:            name,
			OldStart:        oldEntry.Start,
			OldEnd:          oldEntry.Start + oldEntry.N - 1,
			NewStart:        s.Start,
			NewEnd:          s.End,
			ModifiedCount:   modifiedCount,
			CurrentAbout:    oldEntry.About,
			IsAutoGenerated: navblock.IsAutoGenerated(oldEntry.About),
		})
	}

	// Any old entries not matched are deleted.
	for _, e := range oldNav {
		if !usedStart[e.Start] {
			reports = append(reports, ReportEntry{
				Type: ReportDeleted,
				Name: e.Name,
			})
		}
	}

	return reports
}

func buildUpdatedBlock(oldBlock navblock.NavBlock, sections []parser.Section, _ []ReportEntry, lines []string, cfg config.Config, _, totalLines int) navblock.NavBlock {
	// Build multi-map: name -> []NavEntry to handle duplicate heading names.
	// matchSectionsToNav uses exact-match first, then proximity — ensuring each
	// nav entry is paired with the section at the same absolute line before
	// falling back to nearest duplicate.
	byName := navIndex(oldBlock.Nav)
	sectionToEntry, _ := matchSectionsToNav(sections, byName)

	var newNav []navblock.NavEntry

	for i, s := range sections {
		prefix := strings.Repeat("#", s.Depth)
		wc := navblock.SectionWordCount(lines, s.Start, s.Len())

		oldEntry, found := sectionToEntry[i]

		if found {
			about := oldEntry.About
			// Fill empty About fields with auto-generated keywords so that entries
			// which were never described (or were created by an older generate run)
			// get ~keyword descriptions. Human-written abouts (no ~ prefix) are
			// never touched.
			if about == "" {
				about = generate.BuildAboutFromLines(lines, s.Start, s.Start+s.Len()-1)
			}
			newNav = append(newNav, navblock.NavEntry{
				Start:     s.Start,
				N:         s.Len(),
				Name:      prefix + navblock.NormalizeHeading(s.Text),
				About:     about,
				WordCount: wc,
			})
		} else {
			// New section not in the existing nav block.
			// Include all new sections unconditionally — generate now includes ALL
			// sections and lets PruneNavEntries handle the budget. update must do
			// the same: no expandThreshold guard here.
			newNav = append(newNav, navblock.NavEntry{
				Start:     s.Start,
				N:         s.Len(),
				Name:      prefix + navblock.NormalizeHeading(s.Text),
				About:     "",
				WordCount: wc,
			})
		}
	}

	// Only carry forward lines:N if the original block had it.
	outLines := 0
	if oldBlock.Lines != 0 {
		outLines = totalLines
	}

	return navblock.NavBlock{
		Purpose: oldBlock.Purpose,
		Lines:   outLines,
		Nav:     generate.PruneNavEntries(newNav, cfg.SubThreshold, cfg.ExpandThreshold, cfg.MaxNavEntries),
		See:     oldBlock.See,
	}
}

func formatReport(path string, reports []ReportEntry) string {
	var b strings.Builder
	b.WriteString("Updated: ")
	b.WriteString(path)
	b.WriteString("\n")

	hasAutogen := false
	hasAction := false
	for _, r := range reports {
		// Skip OK and shifted entries — they don't need agent attention
		// (shifted is just line number changes, handled automatically)
		if r.Type == ReportOK || r.Type == ReportShifted {
			continue
		}
		hasAction = true
		b.WriteString(r.String())
		b.WriteString("\n")
		if r.IsAutoGenerated {
			hasAutogen = true
		}
	}

	// If no entries need attention, return minimal output
	if !hasAction {
		return "Updated: " + path + " (no changes)"
	}

	if hasAutogen {
		b.WriteString("\n  ⚠ Auto-generated descriptions need review (remove ~ prefix)")
	}

	return strings.TrimSpace(b.String())
}

// filterHintedNewEntries removes "new" entries from the report that were
// collapsed into >hints on parent entries by PruneNavEntries. These entries
// don't need individual abouts and reporting them as "new (no description)"
// is misleading — they're represented by hints.
func filterHintedNewEntries(reports []ReportEntry, nav []navblock.NavEntry) []ReportEntry {
	surviving := make(map[string]bool, len(nav))
	for _, e := range nav {
		surviving[e.Name] = true
	}

	filtered := reports[:0]
	for _, r := range reports {
		if r.Type == ReportNew && !surviving[r.Name] {
			continue
		}
		filtered = append(filtered, r)
	}
	return filtered
}
