// Package generate implements the agentmap generate command.
package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/RKelln/agentmap/internal/config"
	"github.com/RKelln/agentmap/internal/discovery"
	"github.com/RKelln/agentmap/internal/keywords"
	"github.com/RKelln/agentmap/internal/navblock"
	"github.com/RKelln/agentmap/internal/parser"
)

const (
	navBlockEnd = "-->"
)

// Generate discovers markdown files under root and generates nav blocks for each.
func Generate(root string, cfg config.Config, dryRun bool) error {
	files, err := discovery.DiscoverFiles(root, cfg.Exclude)
	if err != nil {
		return fmt.Errorf("generate: discover files: %w", err)
	}

	var anySuccess bool
	for _, f := range files {
		fullPath := filepath.Join(root, f)
		report, err := File(fullPath, cfg, dryRun)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %s: %v\n", f, err)
			continue
		}
		anySuccess = true
		fmt.Println(report)
	}

	if len(files) > 0 && !anySuccess {
		return fmt.Errorf("generate: no files processed successfully")
	}
	return nil
}

// File processes a single markdown file and writes a nav block.
// If outputPath is non-empty, the result is written there instead of modifying the source.
func File(path string, cfg config.Config, dryRun bool, outputPath ...string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("generate: read file: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	// Use strings.Count for totalLines rather than len(lines): strings.Split
	// produces a spurious trailing empty element for POSIX files ending with \n,
	// overcounting by 1. strings.Count("\n") equals wc -l.
	totalLines := strings.Count(string(content), "\n")

	// Check for existing nav block to compute line offset
	blockStart, blockEnd := findNavBlock(lines)
	oldBlockLines := 0
	if blockStart >= 0 {
		oldBlockLines = blockEnd - blockStart + 1
	}

	// Content lines: total newlines minus the nav block itself (0 if no existing block).
	// strings.Count avoids the spurious +1 from strings.Split on trailing newline.
	contentLines := strings.Count(string(content), "\n") - oldBlockLines

	headings, parseWarnings := parser.ParseHeadings(string(content), cfg.MaxDepth)
	for _, w := range parseWarnings {
		fmt.Fprintf(os.Stderr, "warning: %s: %s\n", path, w)
	}
	sections := parser.ComputeSections(headings, totalLines)

	var blockText string
	var report string

	// Use contentLines (not totalLines) for the MinLines threshold: the nav block
	// is infrastructure, not document content — an agent reading the file sees
	// only the content lines, so that is the meaningful size to compare against.
	if contentLines < cfg.MinLines || len(headings) == 0 {
		purpose := keywords.ExtractPurpose(string(content))
		if purpose != "" {
			purpose = navblock.AutoGeneratedPrefix + purpose
		}
		blockText = navblock.RenderPurposeOnly(purpose, contentLines)
		report = fmt.Sprintf("Skipped: %s (purpose-only)", path)
	} else {
		purpose := keywords.ExtractPurpose(string(content))
		if purpose != "" {
			purpose = navblock.AutoGeneratedPrefix + purpose
		}
		// Build nav entries with keyword descriptions from original content (uncapped).
		// buildNavEntries always returns one entry per section, preserving index alignment.
		originalEntries := buildNavEntries(sections, string(content))
		// Compute line offset using the capped entries (what will actually be written),
		// so the block size estimate matches reality.
		cappedForOffset := PruneNavEntries(originalEntries, cfg.SubThreshold, cfg.ExpandThreshold, cfg.MaxNavEntries)
		placeholder := navblock.NavBlock{Purpose: purpose, Lines: contentLines, Nav: cappedForOffset}
		placeholderText := navblock.RenderNavBlock(placeholder)
		// RenderNavBlock does NOT append a trailing newline, so strings.Split here
		// correctly counts lines without the spurious +1 that a trailing \n would cause.
		// If RenderNavBlock ever gains a trailing newline this count would be off by 1.
		newBlockLines := len(strings.Split(placeholderText, "\n"))
		// For fresh files (no existing nav block), insertNavBlock adds a blank separator
		// line after the nav block (via cleanBlankLines). This blank is not part of
		// newBlockLines, so add 1 to account for it. For existing nav blocks the blank
		// was already present, so it cancels out and no adjustment is needed.
		separatorLines := 0
		if oldBlockLines == 0 {
			separatorLines = 1
		}
		offset := newBlockLines + separatorLines - oldBlockLines

		// Shift every entry's Start by the offset. The offset is uniform across all
		// lines in the file (the nav block is prepended), so we apply it directly to
		// the entries rather than trying to align them with the full sections slice.
		// This avoids the previous applyAdjustedLines length guard silently bailing
		// when buildNavEntries skips h3 children (len(entries) < len(sections)).
		adjustedEntries := shiftEntries(originalEntries, offset)
		// Apply the large-file cap AFTER adjusting line numbers so kept entries are correct.
		entries := PruneNavEntries(adjustedEntries, cfg.SubThreshold, cfg.ExpandThreshold, cfg.MaxNavEntries)
		block := navblock.NavBlock{
			Purpose: purpose,
			Lines:   contentLines,
			Nav:     entries,
		}
		blockText = navblock.RenderNavBlock(block)
		report = fmt.Sprintf("Generated: %s (%d sections)", path, len(entries))
	}

	if dryRun {
		return report, nil
	}

	newContent := insertNavBlock(string(content), blockText)

	// Recompute lines:N from the final content so generate/update/index always agree.
	// insertNavBlock adds a blank separator that wasn't in the pre-insertion newline count,
	// so the stored value would be off by 1 on the first generate for fresh files.
	if contentLines > 0 {
		if pr2 := navblock.ParseNavBlock(newContent); pr2.Found {
			finalContentLines := strings.Count(newContent, "\n") - (pr2.End - pr2.Start + 1)
			if finalContentLines < 0 {
				finalContentLines = 0
			}
			if finalContentLines != contentLines {
				old := fmt.Sprintf("lines:%d\n", contentLines)
				repl := fmt.Sprintf("lines:%d\n", finalContentLines)
				blockText = strings.Replace(blockText, old, repl, 1)
				newContent = insertNavBlock(string(content), blockText)
			}
		}
	}

	// Write to output path if specified, otherwise modify source in place
	dest := path
	if len(outputPath) > 0 && outputPath[0] != "" {
		dest = outputPath[0]
	}

	if err := os.WriteFile(dest, []byte(newContent), 0o644); err != nil {
		return "", fmt.Errorf("generate: write file: %w", err)
	}

	return report, nil
}

// shiftEntries returns a copy of entries with each Start shifted by offset.
// N (section length) is unchanged because the whole file shifts uniformly.
func shiftEntries(entries []navblock.NavEntry, offset int) []navblock.NavEntry {
	if offset == 0 {
		return entries
	}
	result := make([]navblock.NavEntry, len(entries))
	for i, e := range entries {
		result[i] = e
		result[i].Start = e.Start + offset
	}
	return result
}

// findNavBlock returns the 0-indexed start and end lines of an existing nav block.
// A nav block is the first non-blank content after optional frontmatter.
// Returns -1,-1 if any non-whitespace, non-nav-block content appears before nav block.
func findNavBlock(lines []string) (start, end int) {
	return navblock.LocateNavBlock(lines)
}

// insertNavBlock inserts or replaces a nav block in file content.
// Skips nav blocks inside fenced code blocks.
func insertNavBlock(content, blockText string) string {
	lines := strings.Split(content, "\n")

	// Check for existing nav block using canonical detection.
	blockStart, blockEnd := navblock.LocateNavBlock(lines)

	if blockStart >= 0 && blockEnd >= 0 {
		// Replace existing block
		before := strings.Join(lines[:blockStart], "\n")
		after := ""
		if blockEnd+1 < len(lines) {
			after = strings.Join(lines[blockEnd+1:], "\n")
		}
		// If before is non-empty it lacks a trailing newline (Join doesn't add one),
		// so add one to prevent the nav block from being fused to the preceding line.
		var result string
		if before != "" {
			result = before + "\n" + blockText + "\n" + after
		} else {
			result = blockText + "\n" + after
		}
		// Clean up extra blank lines
		result = cleanBlankLines(result)
		return result
	}

	// Check for frontmatter and insert after it if present
	if fmEnd := navblock.FindFrontmatterEnd(lines); fmEnd >= 0 {
		before := strings.Join(lines[:fmEnd+1], "\n")
		after := strings.Join(lines[fmEnd+1:], "\n")
		result := before + "\n" + blockText + "\n" + after
		result = cleanBlankLines(result)
		return result
	}

	// Insert at line 1
	result := blockText + "\n" + content
	result = cleanBlankLines(result)
	return result
}

// cleanBlankLines ensures exactly one blank line between nav block and first heading.
func cleanBlankLines(content string) string {
	lines := strings.Split(content, "\n")

	// Find the nav block end
	navEnd := -1
	for i, line := range lines {
		if strings.TrimSpace(line) == navBlockEnd {
			navEnd = i
			break
		}
	}

	if navEnd < 0 {
		return content
	}

	// Count blank lines after nav block
	blankCount := 0
	for i := navEnd + 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "" {
			blankCount++
		} else {
			break
		}
	}

	// We want exactly one blank line
	if blankCount == 0 {
		// Insert a blank line
		newLines := make([]string, 0, len(lines)+1)
		newLines = append(newLines, lines[:navEnd+1]...)
		newLines = append(newLines, "")
		newLines = append(newLines, lines[navEnd+1:]...)
		return strings.Join(newLines, "\n")
	} else if blankCount > 1 {
		// Remove extra blank lines
		newLines := make([]string, 0, len(lines)-blankCount+1)
		newLines = append(newLines, lines[:navEnd+1]...)
		newLines = append(newLines, "")
		newLines = append(newLines, lines[navEnd+1+blankCount:]...)
		return strings.Join(newLines, "\n")
	}

	return content
}

// buildNavEntries converts parser sections to nav entries with keyword descriptions.
// Every section becomes a NavEntry — no threshold-based branching. Pruning is
// performed later by PruneNavEntries based on the total entry count vs max_nav_entries.
func buildNavEntries(sections []parser.Section, content string) []navblock.NavEntry {
	lines := strings.Split(content, "\n")
	entries := make([]navblock.NavEntry, 0, len(sections))

	for _, s := range sections {
		sectionContent := getSectionContent(lines, s.Start, s.End)

		prefix := strings.Repeat("#", s.Depth)
		about := keywords.ExtractKeywords(sectionContent, 5)
		if about != "" {
			about = navblock.AutoGeneratedPrefix + about
		}

		entries = append(entries, navblock.NavEntry{
			Start:     s.Start,
			N:         s.Len(),
			Name:      prefix + navblock.NormalizeHeading(s.Text),
			About:     about,
			WordCount: navblock.SectionWordCount(lines, s.Start, s.Len()),
		})
	}

	return entries
}

// PruneNavEntries applies the §11.4 budget-first algorithm to cap nav entries.
//
// If len(entries) <= maxEntries, the input is returned unchanged (no copy).
// Otherwise entries are pruned depth-first, guided by parent section size:
//   - parent N < subThreshold   → droppable (no hint)
//   - parent N in [sub, expand) → hintable (collapsed to > hint on parent About)
//   - parent N >= expandThreshold → unkillable (kept; overrun accepted)
//   - no parent found            → treat as droppable (parentN = 0)
//
// Within each round the cheapest (shortest N) candidates are pruned first.
// Pruning stops when within budget, when no droppable/hintable entries remain,
// or when only shallow entries (depth ≤ 2) are left.
//
// The function returns a new slice sorted by Start; it does NOT mutate the input.
// It is safe to call twice (e.g. once for offset measurement, once after shift).
func PruneNavEntries(entries []navblock.NavEntry, subThreshold, expandThreshold, maxEntries int) []navblock.NavEntry {
	if len(entries) <= maxEntries {
		return entries
	}

	// Deep-copy entries so we can mutate About fields without touching the original.
	work := make([]navblock.NavEntry, len(entries))
	copy(work, entries)

	for len(work) > maxEntries {

		// Find the deepest depth in the current working set.
		maxD := 0
		for _, e := range work {
			if d := entryNameDepth(e.Name); d > maxD {
				maxD = d
			}
		}

		// Shallow overrun: only depth ≤ 2 entries remain — accept.
		if maxD <= 2 {
			break
		}

		// Collect candidates at maxD and classify them by parent size.
		type candidate struct {
			workIdx  int
			parentN  int
			hintable bool // false → droppable
		}
		var droppable, hintable []candidate

		for i, e := range work {
			if entryNameDepth(e.Name) != maxD {
				continue
			}
			// Find parent: closest preceding entry with depth < maxD.
			parentN := 0
			for j := i - 1; j >= 0; j-- {
				if entryNameDepth(work[j].Name) < maxD {
					parentN = work[j].N
					break
				}
			}

			switch {
			case parentN >= expandThreshold:
				// unkillable — skip
			case parentN >= subThreshold:
				hintable = append(hintable, candidate{i, parentN, true})
			default:
				droppable = append(droppable, candidate{i, parentN, false})
			}
		}

		if len(droppable)+len(hintable) == 0 {
			// All deep entries are unkillable; accept overrun.
			break
		}

		// Merge and sort by N ascending (shortest = cheapest first).
		all := append(droppable, hintable...) //nolint:gocritic
		sort.Slice(all, func(i, j int) bool {
			return work[all[i].workIdx].N < work[all[j].workIdx].N
		})

		// Mark indices to remove; for hintable entries also update parent About.
		remove := make(map[int]bool)
		for _, c := range all {
			if len(work)-len(remove) <= maxEntries {
				break
			}

			idx := c.workIdx
			e := work[idx]
			remove[idx] = true

			if c.hintable {
				// Derive hint text: heading name without leading # chars, commas → semicolons.
				headingText := strings.TrimLeft(e.Name, "#")
				hint := strings.ReplaceAll(headingText, ",", ";")

				// Find parent index and mutate its About.
				for j := idx - 1; j >= 0; j-- {
					if entryNameDepth(work[j].Name) < maxD {
						p := &work[j]
						switch {
						case p.About == "":
							p.About = navblock.AutoGeneratedPrefix + ">" + hint
						case strings.Contains(p.About, ">"):
							p.About += ";" + hint
						default:
							p.About += ">" + hint
						}
						break
					}
				}
			}
		}

		if len(remove) == 0 {
			break
		}

		// Rebuild working set without removed entries.
		next := work[:0]
		for i, e := range work {
			if !remove[i] {
				next = append(next, e)
			}
		}
		work = next
	}

	// Return in document order.
	sort.Slice(work, func(i, j int) bool { return work[i].Start < work[j].Start })
	return work
}

// entryNameDepth returns the heading depth of a nav entry by counting leading '#' chars.
func entryNameDepth(name string) int {
	d := 0
	for _, ch := range name {
		if ch == '#' {
			d++
		} else {
			break
		}
	}
	return d
}

// getSectionContent extracts the text content between start and end line numbers (1-indexed).
func getSectionContent(lines []string, start, end int) string {
	if start < 1 || end < start {
		return ""
	}
	if end > len(lines) {
		end = len(lines)
	}
	return strings.Join(lines[start-1:end], "\n")
}
