// Package generate implements the agentmap generate command.
package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/RKelln/agentmap/internal/config"
	"github.com/RKelln/agentmap/internal/discovery"
	"github.com/RKelln/agentmap/internal/keywords"
	"github.com/RKelln/agentmap/internal/navblock"
	"github.com/RKelln/agentmap/internal/parser"
)

const (
	navBlockEnd = "-->"
)

// Generate discovers markdown files under root and generates nav blocks for each.
func Generate(root string, cfg config.Config, dryRun bool) error {
	files, err := discovery.DiscoverFiles(root, cfg.Exclude)
	if err != nil {
		return fmt.Errorf("generate: discover files: %w", err)
	}

	var anySuccess bool
	for _, f := range files {
		fullPath := filepath.Join(root, f)
		report, err := File(fullPath, cfg, dryRun)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %s: %v\n", f, err)
			continue
		}
		anySuccess = true
		fmt.Println(report)
	}

	if len(files) > 0 && !anySuccess {
		return fmt.Errorf("generate: no files processed successfully")
	}
	return nil
}

// File processes a single markdown file and writes a nav block.
// If outputPath is non-empty, the result is written there instead of modifying the source.
func File(path string, cfg config.Config, dryRun bool, outputPath ...string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("generate: read file: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	totalLines := len(lines)

	// Check for existing nav block to compute line offset
	blockStart, blockEnd := findNavBlock(lines)
	oldBlockLines := 0
	if blockStart >= 0 {
		oldBlockLines = blockEnd - blockStart + 1
	}

	// Content lines: total newlines minus the nav block itself (0 if no existing block).
	// strings.Count avoids the spurious +1 from strings.Split on trailing newline.
	contentLines := strings.Count(string(content), "\n") - oldBlockLines

	headings := parser.ParseHeadings(string(content), cfg.MaxDepth)
	sections := parser.ComputeSections(headings, totalLines)

	var blockText string
	var report string

	if totalLines < cfg.MinLines || len(headings) == 0 {
		purpose := keywords.ExtractPurpose(string(content))
		if purpose != "" {
			purpose = navblock.AutoGeneratedPrefix + purpose
		}
		blockText = navblock.RenderPurposeOnly(purpose, contentLines)
		report = fmt.Sprintf("Skipped: %s (purpose-only)", path)
	} else {
		purpose := keywords.ExtractPurpose(string(content))
		if purpose != "" {
			purpose = navblock.AutoGeneratedPrefix + purpose
		}
		// Build nav entries with keyword descriptions from original content (uncapped).
		// buildNavEntries always returns one entry per section, preserving index alignment.
		originalEntries := buildNavEntries(sections, string(content), cfg)
		// Compute line offset using the capped entries (what will actually be written),
		// so the block size estimate matches reality.
		cappedForOffset := FilterNavEntries(originalEntries, cfg.MaxNavEntries, cfg.NavStubWords)
		placeholder := navblock.NavBlock{Purpose: purpose, Lines: contentLines, Nav: cappedForOffset}
		placeholderText := navblock.RenderNavBlock(placeholder)
		newBlockLines := len(strings.Split(placeholderText, "\n"))
		// For fresh files (no existing nav block), insertNavBlock adds a blank separator
		// line after the nav block (via cleanBlankLines). This blank is not part of
		// newBlockLines, so add 1 to account for it. For existing nav blocks the blank
		// was already present, so it cancels out and no adjustment is needed.
		separatorLines := 0
		if oldBlockLines == 0 {
			separatorLines = 1
		}
		offset := newBlockLines + separatorLines - oldBlockLines

		// Shift every entry's Start by the offset. The offset is uniform across all
		// lines in the file (the nav block is prepended), so we apply it directly to
		// the entries rather than trying to align them with the full sections slice.
		// This avoids the previous applyAdjustedLines length guard silently bailing
		// when buildNavEntries skips h3 children (len(entries) < len(sections)).
		adjustedEntries := shiftEntries(originalEntries, offset)
		// Apply the large-file cap AFTER adjusting line numbers so kept entries are correct.
		entries := FilterNavEntries(adjustedEntries, cfg.MaxNavEntries, cfg.NavStubWords)
		block := navblock.NavBlock{
			Purpose: purpose,
			Lines:   contentLines,
			Nav:     entries,
		}
		blockText = navblock.RenderNavBlock(block)
		report = fmt.Sprintf("Generated: %s (%d sections)", path, len(entries))
	}

	if dryRun {
		return report, nil
	}

	newContent := insertNavBlock(string(content), blockText)

	// Recompute lines:N from the final content so generate/update/index always agree.
	// insertNavBlock adds a blank separator that wasn't in the pre-insertion newline count,
	// so the stored value would be off by 1 on the first generate for fresh files.
	if contentLines > 0 {
		if pr2 := navblock.ParseNavBlock(newContent); pr2.Found {
			finalContentLines := strings.Count(newContent, "\n") - (pr2.End - pr2.Start + 1)
			if finalContentLines < 0 {
				finalContentLines = 0
			}
			if finalContentLines != contentLines {
				old := fmt.Sprintf("lines:%d\n", contentLines)
				repl := fmt.Sprintf("lines:%d\n", finalContentLines)
				blockText = strings.Replace(blockText, old, repl, 1)
				newContent = insertNavBlock(string(content), blockText)
			}
		}
	}

	// Write to output path if specified, otherwise modify source in place
	dest := path
	if len(outputPath) > 0 && outputPath[0] != "" {
		dest = outputPath[0]
	}

	if err := os.WriteFile(dest, []byte(newContent), 0o644); err != nil {
		return "", fmt.Errorf("generate: write file: %w", err)
	}

	return report, nil
}

// shiftEntries returns a copy of entries with each Start shifted by offset.
// N (section length) is unchanged because the whole file shifts uniformly.
func shiftEntries(entries []navblock.NavEntry, offset int) []navblock.NavEntry {
	if offset == 0 {
		return entries
	}
	result := make([]navblock.NavEntry, len(entries))
	for i, e := range entries {
		result[i] = e
		result[i].Start = e.Start + offset
	}
	return result
}

// findNavBlock returns the 0-indexed start and end lines of an existing nav block.
// A nav block is the first non-blank content after optional frontmatter.
// Returns -1,-1 if any non-whitespace, non-nav-block content appears before nav block.
func findNavBlock(lines []string) (start, end int) {
	return navblock.LocateNavBlock(lines)
}

// insertNavBlock inserts or replaces a nav block in file content.
// Skips nav blocks inside fenced code blocks.
func insertNavBlock(content string, blockText string) string {
	lines := strings.Split(content, "\n")

	// Check for existing nav block using canonical detection.
	blockStart, blockEnd := navblock.LocateNavBlock(lines)

	if blockStart >= 0 && blockEnd >= 0 {
		// Replace existing block
		before := strings.Join(lines[:blockStart], "\n")
		after := ""
		if blockEnd+1 < len(lines) {
			after = strings.Join(lines[blockEnd+1:], "\n")
		}
		// If before is non-empty it lacks a trailing newline (Join doesn't add one),
		// so add one to prevent the nav block from being fused to the preceding line.
		var result string
		if before != "" {
			result = before + "\n" + blockText + "\n" + after
		} else {
			result = blockText + "\n" + after
		}
		// Clean up extra blank lines
		result = cleanBlankLines(result)
		return result
	}

	// Check for frontmatter and insert after it if present
	if fmEnd := navblock.FindFrontmatterEnd(lines); fmEnd >= 0 {
		before := strings.Join(lines[:fmEnd+1], "\n")
		after := strings.Join(lines[fmEnd+1:], "\n")
		result := before + "\n" + blockText + "\n" + after
		result = cleanBlankLines(result)
		return result
	}

	// Insert at line 1
	result := blockText + "\n" + content
	result = cleanBlankLines(result)
	return result
}

// cleanBlankLines ensures exactly one blank line between nav block and first heading.
func cleanBlankLines(content string) string {
	lines := strings.Split(content, "\n")

	// Find the nav block end
	navEnd := -1
	for i, line := range lines {
		if strings.TrimSpace(line) == navBlockEnd {
			navEnd = i
			break
		}
	}

	if navEnd < 0 {
		return content
	}

	// Count blank lines after nav block
	blankCount := 0
	for i := navEnd + 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "" {
			blankCount++
		} else {
			break
		}
	}

	// We want exactly one blank line
	if blankCount == 0 {
		// Insert a blank line
		newLines := make([]string, 0, len(lines)+1)
		newLines = append(newLines, lines[:navEnd+1]...)
		newLines = append(newLines, "")
		newLines = append(newLines, lines[navEnd+1:]...)
		return strings.Join(newLines, "\n")
	} else if blankCount > 1 {
		// Remove extra blank lines
		newLines := make([]string, 0, len(lines)-blankCount+1)
		newLines = append(newLines, lines[:navEnd+1]...)
		newLines = append(newLines, "")
		newLines = append(newLines, lines[navEnd+1+blankCount:]...)
		return strings.Join(newLines, "\n")
	}

	return content
}

// buildNavEntries converts parser sections to nav entries with keyword descriptions.
// Applies three-tier subsection logic:
//   - Under subThreshold: no subsection info (h3 children skipped)
//   - Between subThreshold and expandThreshold: > hints for h3 children (h3 skipped)
//   - Over expandThreshold: full h3 entries as separate nav entries
func buildNavEntries(sections []parser.Section, content string, cfg config.Config) []navblock.NavEntry {
	lines := strings.Split(content, "\n")
	var entries []navblock.NavEntry
	skipUntil := 0 // track sections to skip (h3 children of parents not expanding)

	for i, s := range sections {
		if s.Start < skipUntil {
			continue
		}

		sectionContent := getSectionContent(lines, s.Start, s.End)
		sectionSize := s.Len()

		prefix := strings.Repeat("#", s.Depth)
		about := keywords.ExtractKeywords(sectionContent, 5)
		if about != "" {
			about = navblock.AutoGeneratedPrefix + about
		}

		// Apply subsection logic for h2 entries (depth 2) with h3 children
		if s.Depth == 2 {
			h3Children := getH3Children(sections, i)

			if sectionSize >= cfg.ExpandThreshold {
				// Full expansion: add h3 children as separate entries
				entries = append(entries, navblock.NavEntry{
					Start:     s.Start,
					N:         s.Len(),
					Name:      prefix + navblock.NormalizeHeading(s.Text),
					About:     about,
					WordCount: navblock.SectionWordCount(lines, s.Start, s.Len()),
				})
				for _, child := range h3Children {
					childContent := getSectionContent(lines, child.Start, child.End)
					childAbout := keywords.ExtractKeywords(childContent, 5)
					if childAbout != "" {
						childAbout = navblock.AutoGeneratedPrefix + childAbout
					}
					childPrefix := strings.Repeat("#", child.Depth)
					entries = append(entries, navblock.NavEntry{
						Start:     child.Start,
						N:         child.Len(),
						Name:      childPrefix + navblock.NormalizeHeading(child.Text),
						About:     childAbout,
						WordCount: navblock.SectionWordCount(lines, child.Start, child.Len()),
					})
				}
				// Skip past h3 children so they're not processed again as standalone entries
				if len(h3Children) > 0 {
					skipUntil = h3Children[len(h3Children)-1].Start + 1
				}
				continue
			} else if len(h3Children) > 0 {
				// Small or medium section: skip h3 children
				skipUntil = h3Children[len(h3Children)-1].Start + 1
				// Only add > hints for medium sections (>= sub_threshold)
				if sectionSize >= cfg.SubThreshold {
					hints := make([]string, len(h3Children))
					for j, child := range h3Children {
						hints[j] = strings.ReplaceAll(child.Text, ",", ";")
					}
					if about != "" {
						about += ">" + strings.Join(hints, ";")
					} else {
						about = navblock.AutoGeneratedPrefix + ">" + strings.Join(hints, ";")
					}
				}
			}
		}

		entries = append(entries, navblock.NavEntry{
			Start:     s.Start,
			N:         s.Len(),
			Name:      prefix + navblock.NormalizeHeading(s.Text),
			About:     about,
			WordCount: navblock.SectionWordCount(lines, s.Start, s.Len()),
		})
	}

	// §11.4: large-file cap is applied after applyAdjustedLines (in Generate/File),
	// not here, so line numbers are adjusted first.
	return entries
}

// FilterNavEntries applies the §11.4 large-file cap using a two-pass soft algorithm:
//
// Pass 1 (stub): remove h3+ candidates with WordCount < stubWords (trivially empty sections).
// Pass 2 (budget): if candidates still exceed budget (maxEntries - len(fixed)),
// keep only the longest `budget` candidates.
//
// Entries at depth ≤ 2 (h1/h2) are always kept (fixed). If fixed alone exceed
// maxEntries, the overrun is accepted and all entries are returned unchanged.
// The result is always returned in document order (ascending Start line).
//
// This is exported so check and update can apply the same cap for consistency.
func FilterNavEntries(entries []navblock.NavEntry, maxEntries, stubWords int) []navblock.NavEntry {
	var fixed, candidates []navblock.NavEntry
	for _, e := range entries {
		d := 0
		for _, ch := range e.Name {
			if ch == '#' {
				d++
			} else {
				break
			}
		}
		if d <= 2 {
			fixed = append(fixed, e)
		} else {
			candidates = append(candidates, e)
		}
	}

	// No cap needed
	if len(fixed)+len(candidates) <= maxEntries {
		return entries
	}

	// Pass 1: remove stubs (candidates with WordCount < stubWords)
	kept := candidates[:0]
	for _, c := range candidates {
		if c.WordCount >= stubWords {
			kept = append(kept, c)
		}
	}
	candidates = kept

	// Recheck after stub pass
	if len(fixed)+len(candidates) <= maxEntries {
		// Reconstruct in document order
		merged := append(fixed, candidates...) //nolint:gocritic
		sort.Slice(merged, func(i, j int) bool { return merged[i].Start < merged[j].Start })
		return merged
	}

	// Pass 2: budget pass — keep the longest `budget` candidates
	budget := maxEntries - len(fixed)
	if budget <= 0 {
		// h1/h2 already at or over cap; drop all candidates
		sort.Slice(fixed, func(i, j int) bool { return fixed[i].Start < fixed[j].Start })
		return fixed
	}
	if len(candidates) > budget {
		// Sort by n ascending, keep the last `budget` (longest)
		sort.Slice(candidates, func(i, j int) bool { return candidates[i].N < candidates[j].N })
		candidates = candidates[len(candidates)-budget:]
	}

	// Reconstruct in document order
	merged := append(fixed, candidates...) //nolint:gocritic
	sort.Slice(merged, func(i, j int) bool { return merged[i].Start < merged[j].Start })
	return merged
}

// getSectionContent extracts the text content between start and end line numbers (1-indexed).
func getSectionContent(lines []string, start, end int) string {
	if start < 1 || end < start {
		return ""
	}
	if end > len(lines) {
		end = len(lines)
	}
	return strings.Join(lines[start-1:end], "\n")
}

// getH3Children returns h3 sections that are immediate children of the section at index i.
func getH3Children(sections []parser.Section, parentIdx int) []parser.Section {
	if parentIdx+1 >= len(sections) {
		return nil
	}

	parent := sections[parentIdx]
	if parent.Depth != 2 {
		return nil
	}

	var children []parser.Section
	for j := parentIdx + 1; j < len(sections); j++ {
		s := sections[j]
		// Stop at any heading at same or higher level (h1 or h2)
		if s.Depth <= parent.Depth {
			break
		}
		// Only include h3 that starts within parent's span
		if s.Depth == 3 && s.Start <= parent.End {
			children = append(children, s)
		}
	}

	return children
}
